syntax = "proto3";

import "google/protobuf/wrappers.proto";

service ProductService {
  rpc Save(SaveProductsMessage) returns (ResultMessage);
  rpc SaveFeatureValues(SaveFeatureValuesMessage) returns (ResultMessage);
  rpc SaveDimensions(SaveDimensionsMessage) returns (ResultMessage);
  rpc ClearAvailableBySupplierWarehouseId(ClearAvailableMessage) returns (ResultMessage);
}

message ResultMessage {
  repeated string warnings = 1;
  optional ErrorMessage error_obj = 2;
}

message ErrorMessage {
  string error_message = 1;
  repeated ErrorMessage details = 2;
}

message SaveProductsMessage {
  int32 parser_settings_id = 1;
  repeated ProductMessage products = 2;
}

message SaveDimensionsMessage {
  int32 parser_settings_id = 1;
  repeated ProductAliasDimensionsMessage product_dimensions = 2;
}

message SaveFeatureValuesMessage {
  int32 parser_settings_id = 1;
  repeated FeatureValueMessage feature_values = 2;
}

message ProductMessage {
  optional google.protobuf.StringValue code = 1;
  optional google.protobuf.StringValue name = 2;
  optional google.protobuf.StringValue pn = 3;
  optional google.protobuf.StringValue barcode = 4;
  optional google.protobuf.StringValue link = 5;
  optional google.protobuf.Int64Value tnved = 6;
  optional AvailType avail_type = 7;
  repeated PriceMessage prices = 8;
  repeated SupplierWarehouseAvailMessage supplier_warehouse_avails = 9;
  optional google.protobuf.StringValue category = 10;
  optional google.protobuf.StringValue full_category = 11;
  optional google.protobuf.Int32Value parser_category_id = 12;
}

message PriceMessage {
  double value = 1;
  Currency currency = 2;
  PriceType price_type = 3;

  enum Currency {
    NONE_CURRENCY = 0;
    UAH = 1;
    USD = 2;
    EUR = 3;
  }

  enum PriceType {
    NONE_PRICE_TYPE = 0;
    RRP = 1;
    RETAIL = 2;
    WHOLESALE = 3;
    CONFIGURATOR = 4;
  }
}

message ProductAliasDimensionsMessage {

  string product_alias_ref = 1;
  optional google.protobuf.DoubleValue width = 2;
  optional google.protobuf.DoubleValue height = 3;
  optional google.protobuf.DoubleValue length = 4;
  optional google.protobuf.DoubleValue weight = 5;
  optional Unit unit_size_id = 6;
  optional Unit unit_weight_id = 7;

  enum Unit {
    NONE_UNIT = 0;
    KILOGRAM = 1;
    CENTIMETER = 2;
    GRAM = 3;
    MILLIMETER = 4;
  }
}

message FeatureValueMessage {
  string product_alias_ref = 1;
  string external_id = 2;
  string feature_name = 3;
  string feature_value = 4;
}

message SupplierWarehouseAvailMessage {
  int32 supplier_warehouse_id = 1;
  string price_avail = 2;
  AvailType avail_type = 3;
  int32 quantity = 4;
  optional google.protobuf.StringValue supplier_warehouse_name = 5;
}

message ClearAvailableMessage{
    int32 contractor_id = 1;
}

enum AvailType {
  NONE_AVAIL_TYPE = 0;
  AVAIL = 1;
  COMING_SOON = 2;
  CLARIFY = 3;
  NOT_AVAIL = 4;
}