//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telemart.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Telemart.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тариф Admitad.
        /// </summary>
        public static string CategoryEditingData_AdmitadTariffCode {
            get {
                return ResourceManager.GetString("CategoryEditingData_AdmitadTariffCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бухгалтерия.
        /// </summary>
        public static string CategoryEditingData_Bookkeeping {
            get {
                return ResourceManager.GetString("CategoryEditingData_Bookkeeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контент.
        /// </summary>
        public static string CategoryEditingData_Content {
            get {
                return ResourceManager.GetString("CategoryEditingData_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполнять комплектацию.
        /// </summary>
        public static string CategoryEditingData_Content__NeedComplect {
            get {
                return ResourceManager.GetString("CategoryEditingData_Content__NeedComplect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполнить за (дней).
        /// </summary>
        public static string CategoryEditingData_Content_DaysToFill {
            get {
                return ResourceManager.GetString("CategoryEditingData_Content_DaysToFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполнять контент.
        /// </summary>
        public static string CategoryEditingData_Content_NeedContent {
            get {
                return ResourceManager.GetString("CategoryEditingData_Content_NeedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во символов.
        /// </summary>
        public static string CategoryEditingData_Content_NeedDescription {
            get {
                return ResourceManager.GetString("CategoryEditingData_Content_NeedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во фото.
        /// </summary>
        public static string CategoryEditingData_Content_NeedPhoto {
            get {
                return ResourceManager.GetString("CategoryEditingData_Content_NeedPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполнять видео.
        /// </summary>
        public static string CategoryEditingData_Content_NeedVideo {
            get {
                return ResourceManager.GetString("CategoryEditingData_Content_NeedVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основные.
        /// </summary>
        public static string CategoryEditingData_Main {
            get {
                return ResourceManager.GetString("CategoryEditingData_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активна.
        /// </summary>
        public static string CategoryEditingData_Main_Active {
            get {
                return ResourceManager.GetString("CategoryEditingData_Main_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код 1С.
        /// </summary>
        public static string CategoryEditingData_Main_Category1C {
            get {
                return ResourceManager.GetString("CategoryEditingData_Main_Category1C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код сайта.
        /// </summary>
        public static string CategoryEditingData_Main_CategoryId {
            get {
                return ResourceManager.GetString("CategoryEditingData_Main_CategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Род. категория.
        /// </summary>
        public static string CategoryEditingData_Main_IsParent {
            get {
                return ResourceManager.GetString("CategoryEditingData_Main_IsParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Производитель.
        /// </summary>
        public static string CategoryEditingData_Main_Manufactor {
            get {
                return ResourceManager.GetString("CategoryEditingData_Main_Manufactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название (рус.).
        /// </summary>
        public static string CategoryEditingData_Main_Name {
            get {
                return ResourceManager.GetString("CategoryEditingData_Main_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название (англ.).
        /// </summary>
        public static string CategoryEditingData_Main_NameEn {
            get {
                return ResourceManager.GetString("CategoryEditingData_Main_NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название (укр.).
        /// </summary>
        public static string CategoryEditingData_Main_NameUkr {
            get {
                return ResourceManager.GetString("CategoryEditingData_Main_NameUkr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код родителя.
        /// </summary>
        public static string CategoryEditingData_Main_ParentId {
            get {
                return ResourceManager.GetString("CategoryEditingData_Main_ParentId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Стоимость услуг Trade-In.
        /// </summary>
        public static string CategoryEditingData_Main_Trade_In_Cost {
            get {
                return ResourceManager.GetString("CategoryEditingData_Main_Trade_In_Cost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Валюта.
        /// </summary>
        public static string CategoryEditingData_Main_Trade_In_Cost_Currency {
            get {
                return ResourceManager.GetString("CategoryEditingData_Main_Trade_In_Cost_Currency", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Использовать в Trade-In.
        /// </summary>
        public static string CategoryEditingData_Main_Use_In_Trade_In {
            get {
                return ResourceManager.GetString("CategoryEditingData_Main_Use_In_Trade_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код Яндекс.Маркет (HID).
        /// </summary>
        public static string CategoryEditingData_Main_YandexMarketHid {
            get {
                return ResourceManager.GetString("CategoryEditingData_Main_YandexMarketHid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маска характеристик.
        /// </summary>
        public static string CategoryEditingData_Mask {
            get {
                return ResourceManager.GetString("CategoryEditingData_Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Префикс.
        /// </summary>
        public static string CategoryEditingData_Prefix {
            get {
                return ResourceManager.GetString("CategoryEditingData_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На английском.
        /// </summary>
        public static string CategoryEditingData_Prefix_PrefixEn {
            get {
                return ResourceManager.GetString("CategoryEditingData_Prefix_PrefixEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На русском.
        /// </summary>
        public static string CategoryEditingData_Prefix_PrefixRus {
            get {
                return ResourceManager.GetString("CategoryEditingData_Prefix_PrefixRus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На украинском.
        /// </summary>
        public static string CategoryEditingData_Prefix_PrefixUkr {
            get {
                return ResourceManager.GetString("CategoryEditingData_Prefix_PrefixUkr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры.
        /// </summary>
        public static string CategoryEditingData_Properties {
            get {
                return ResourceManager.GetString("CategoryEditingData_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валюта.
        /// </summary>
        public static string CategoryEditingData_Properties_Currency {
            get {
                return ResourceManager.GetString("CategoryEditingData_Properties_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответственный.
        /// </summary>
        public static string CategoryEditingData_Properties_EmployeeId {
            get {
                return ResourceManager.GetString("CategoryEditingData_Properties_EmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закупает.
        /// </summary>
        public static string CategoryEditingData_Properties_EmployeeSupId {
            get {
                return ResourceManager.GetString("CategoryEditingData_Properties_EmployeeSupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бесплатная доставка.
        /// </summary>
        public static string CategoryEditingData_Properties_FreeDelivery {
            get {
                return ResourceManager.GetString("CategoryEditingData_Properties_FreeDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учет габаритов.
        /// </summary>
        public static string CategoryEditingData_Properties_KeepDimensions {
            get {
                return ResourceManager.GetString("CategoryEditingData_Properties_KeepDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учет PN.
        /// </summary>
        public static string CategoryEditingData_Properties_KeepPn {
            get {
                return ResourceManager.GetString("CategoryEditingData_Properties_KeepPn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учет SN.
        /// </summary>
        public static string CategoryEditingData_Properties_KeepSerial {
            get {
                return ResourceManager.GetString("CategoryEditingData_Properties_KeepSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид товара.
        /// </summary>
        public static string CategoryEditingData_Properties_Kind {
            get {
                return ResourceManager.GetString("CategoryEditingData_Properties_Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название компании.
        /// </summary>
        public static string CategoryEditingData_Properties_Manufacture {
            get {
                return ResourceManager.GetString("CategoryEditingData_Properties_Manufacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string CategoryEditingData_Properties_Manufacture_Address {
            get {
                return ResourceManager.GetString("CategoryEditingData_Properties_Manufacture_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Характеристика.
        /// </summary>
        public static string CategoryEditingData_Properties_Manufacture_ProductFeatures {
            get {
                return ResourceManager.GetString("CategoryEditingData_Properties_Manufacture_ProductFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печатать етикетки.
        /// </summary>
        public static string CategoryEditingData_Properties_PrintLabels {
            get {
                return ResourceManager.GetString("CategoryEditingData_Properties_PrintLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наш гар. талон.
        /// </summary>
        public static string CategoryEditingData_Properties_PrintWarrantyCard {
            get {
                return ResourceManager.GetString("CategoryEditingData_Properties_PrintWarrantyCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наш собственный ШК.
        /// </summary>
        public static string CategoryEditingData_Properties_SelfBarcode {
            get {
                return ResourceManager.GetString("CategoryEditingData_Properties_SelfBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое название для 1С.
        /// </summary>
        public static string CategoryEditingData_Properties_ShortName1c {
            get {
                return ResourceManager.GetString("CategoryEditingData_Properties_ShortName1c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хрупкое.
        /// </summary>
        public static string CategoryEditingData_Properties_StickerFragile {
            get {
                return ResourceManager.GetString("CategoryEditingData_Properties_StickerFragile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перемещать вертикально.
        /// </summary>
        public static string CategoryEditingData_Properties_StickerThisWayUp {
            get {
                return ResourceManager.GetString("CategoryEditingData_Properties_StickerThisWayUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курс USD.
        /// </summary>
        public static string CategoryEditingData_Properties_UsdCurrency {
            get {
                return ResourceManager.GetString("CategoryEditingData_Properties_UsdCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гарантия розница.
        /// </summary>
        public static string CategoryEditingData_Properties_WarrantyRetail {
            get {
                return ResourceManager.GetString("CategoryEditingData_Properties_WarrantyRetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гарантия опт.
        /// </summary>
        public static string CategoryEditingData_Properties_WarrantyWholesale {
            get {
                return ResourceManager.GetString("CategoryEditingData_Properties_WarrantyWholesale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вес (кг).
        /// </summary>
        public static string CategoryEditingData_Properties_Weight {
            get {
                return ResourceManager.GetString("CategoryEditingData_Properties_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Робот.
        /// </summary>
        public static string CategoryEditingData_Robot {
            get {
                return ResourceManager.GetString("CategoryEditingData_Robot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим робота (авто).
        /// </summary>
        public static string CategoryEditingData_Robot_RobotModeAuto {
            get {
                return ResourceManager.GetString("CategoryEditingData_Robot_RobotModeAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим робота (ручн.).
        /// </summary>
        public static string CategoryEditingData_Robot_RobotModeManual {
            get {
                return ResourceManager.GetString("CategoryEditingData_Robot_RobotModeManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формулы (вычисления).
        /// </summary>
        public static string CategoryEditingData_Robot_RobotScript {
            get {
                return ResourceManager.GetString("CategoryEditingData_Robot_RobotScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формулы (параметры).
        /// </summary>
        public static string CategoryEditingData_Robot_RobotScriptParameters {
            get {
                return ResourceManager.GetString("CategoryEditingData_Robot_RobotScriptParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тариф SalesDoubler.
        /// </summary>
        public static string CategoryEditingData_SalesDoublerTariffCode {
            get {
                return ResourceManager.GetString("CategoryEditingData_SalesDoublerTariffCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат ценника.
        /// </summary>
        public static string CategoryEditingData_TagFormat {
            get {
                return ResourceManager.GetString("CategoryEditingData_TagFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ставка НДС.
        /// </summary>
        public static string CategoryEditingData_TaxRate {
            get {
                return ResourceManager.GetString("CategoryEditingData_TaxRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Торговые площадки.
        /// </summary>
        public static string CategoryEditingData_TradingPlaces {
            get {
                return ResourceManager.GetString("CategoryEditingData_TradingPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotline.
        /// </summary>
        public static string CategoryEditingData_TradingPlaces_Hotline {
            get {
                return ResourceManager.GetString("CategoryEditingData_TradingPlaces_Hotline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string CategoryEditingData_Type {
            get {
                return ResourceManager.GetString("CategoryEditingData_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите город.
        /// </summary>
        public static string CreateEmployeeViewModel_CityRequired {
            get {
                return ResourceManager.GetString("CreateEmployeeViewModel_CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя.
        /// </summary>
        public static string CreateEmployeeViewModel_NameRequired {
            get {
                return ResourceManager.GetString("CreateEmployeeViewModel_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя транслитом.
        /// </summary>
        public static string CreateEmployeeViewModel_NameTranslitRequired {
            get {
                return ResourceManager.GetString("CreateEmployeeViewModel_NameTranslitRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите подтверждение пароля.
        /// </summary>
        public static string CreateEmployeeViewModel_PasswordConfirmationRequired {
            get {
                return ResourceManager.GetString("CreateEmployeeViewModel_PasswordConfirmationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль.
        /// </summary>
        public static string CreateEmployeeViewModel_PasswordRequired {
            get {
                return ResourceManager.GetString("CreateEmployeeViewModel_PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите подразделение.
        /// </summary>
        public static string CreateEmployeeViewModel_SubdivisionRequired {
            get {
                return ResourceManager.GetString("CreateEmployeeViewModel_SubdivisionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите фамилию.
        /// </summary>
        public static string CreateEmployeeViewModel_SurnameRequired {
            get {
                return ResourceManager.GetString("CreateEmployeeViewModel_SurnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите фамилию транслитом.
        /// </summary>
        public static string CreateEmployeeViewModel_SurnameTranslitRequired {
            get {
                return ResourceManager.GetString("CreateEmployeeViewModel_SurnameTranslitRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при загрузке данных.
        /// </summary>
        public static string ErrorDuringDataLoading {
            get {
                return ResourceManager.GetString("ErrorDuringDataLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при выполнении операции.
        /// </summary>
        public static string ErrorExecutingOperation {
            get {
                return ResourceManager.GetString("ErrorExecutingOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас нет прав на выполнение операции.
        /// </summary>
        public static string ErrorForbidden {
            get {
                return ResourceManager.GetString("ErrorForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LoginWindow_Tittle {
            get {
                return ResourceManager.GetString("LoginWindow_Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение.
        /// </summary>
        public static string MessageBox_ConfirmationCaption {
            get {
                return ResourceManager.GetString("MessageBox_ConfirmationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string MessageBox_ErrorCaption {
            get {
                return ResourceManager.GetString("MessageBox_ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        public static string MessageBox_InformationCaption {
            get {
                return ResourceManager.GetString("MessageBox_InformationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопрос.
        /// </summary>
        public static string MessageBox_QuestionCaption {
            get {
                return ResourceManager.GetString("MessageBox_QuestionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание.
        /// </summary>
        public static string MessageBox_WarningCaption {
            get {
                return ResourceManager.GetString("MessageBox_WarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите способ доставки.
        /// </summary>
        public static string OrderViewModel_CarryType {
            get {
                return ResourceManager.GetString("OrderViewModel_CarryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите город.
        /// </summary>
        public static string OrderViewModel_City {
            get {
                return ResourceManager.GetString("OrderViewModel_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите клиента.
        /// </summary>
        public static string OrderViewModel_Contractor {
            get {
                return ResourceManager.GetString("OrderViewModel_Contractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите корректно e-mail покупателя.
        /// </summary>
        public static string OrderViewModel_Email {
            get {
                return ResourceManager.GetString("OrderViewModel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите источник заказа.
        /// </summary>
        public static string OrderViewModel_OrderSource {
            get {
                return ResourceManager.GetString("OrderViewModel_OrderSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите способ оплаты.
        /// </summary>
        public static string OrderViewModel_PaymentType {
            get {
                return ResourceManager.GetString("OrderViewModel_PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите телефон покупателя.
        /// </summary>
        public static string OrderViewModel_Phone1 {
            get {
                return ResourceManager.GetString("OrderViewModel_Phone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите подразделение.
        /// </summary>
        public static string OrderViewModel_Subdivision {
            get {
                return ResourceManager.GetString("OrderViewModel_Subdivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите склад.
        /// </summary>
        public static string OrderViewModel_Warehouse {
            get {
                return ResourceManager.GetString("OrderViewModel_Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telemart.Client.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле обязательно для заполнения.
        /// </summary>
        public static string RequiredErrorMessage {
            get {
                return ResourceManager.GetString("RequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка связи с сервером.
        /// </summary>
        public static string ServerConnectError {
            get {
                return ResourceManager.GetString("ServerConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервер недоступен.
        /// </summary>
        public static string ServerUnavailable {
            get {
                return ResourceManager.GetString("ServerUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От менеджера.
        /// </summary>
        public static string ServiceRequestDiscussionStateManagerMessage {
            get {
                return ResourceManager.GetString("ServiceRequestDiscussionStateManagerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        public static string ServiceRequestDiscussionStateNoMessage {
            get {
                return ResourceManager.GetString("ServiceRequestDiscussionStateNoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От сервиса.
        /// </summary>
        public static string ServiceRequestDiscussionStateServiceMessage {
            get {
                return ResourceManager.GetString("ServiceRequestDiscussionStateServiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите корректно e-mail клиента.
        /// </summary>
        public static string TradeInViewModel_Email {
            get {
                return ResourceManager.GetString("TradeInViewModel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение вне диапазона.
        /// </summary>
        public static string ValueOutOfRangeErrorMessage {
            get {
                return ResourceManager.GetString("ValueOutOfRangeErrorMessage", resourceCulture);
            }
        }
    }
}
