pipelines:
  default:
    - step:
        script:
          - echo $CodeCommitKey > ~/.ssh/codecommit_rsa.tmp
          - base64 -di ~/.ssh/codecommit_rsa.tmp > ~/.ssh/codecommit_rsa
          - chmod 400 ~/.ssh/codecommit_rsa
          - echo $CodeCommitConfig > ~/.ssh/config.tmp
          - base64 -di  ~/.ssh/config.tmp > ~/.ssh/config
          - chmod 600 ~/.ssh/config
          - cat ~/.ssh/config
          - set +e
          - echo "create-repository --repository-name $BITBUCKET_REPO_FULL_NAME"
          - ssh -o StrictHostKeyChecking=no $CodeCommitHost "create-repository --repository-name $BITBUCKET_REPO_FULL_NAME"
          - set -e
          - echo $BITBUCKET_REPO_SLUG
          - git remote add codecommit ssh://$CodeCommitHost/v1/repos/$BITBUCKET_REPO_SLUG
          - git push codecommit $BITBUCKET_BRANCH