<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Platforms>AnyCPU</Platforms>
    <Configurations>Debug;Release</Configurations>
	<LangVersion>8</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Geometria\Geometria.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Geometria\Geometria.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.13.61">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Drawing.Common" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\client\Telemart.Client.Core\Telemart.Client.Core.csproj" />
  </ItemGroup>

</Project>
