using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Windows;
using DevExpress.Xpf.Grid;
using Telemart.Client.Core;

namespace Telemart.Client.Common.Behaviors
{
    internal sealed class LayoutSerializationBehavior : BehaviorBase<GridControl>
    {
        private readonly List<LayoutChangedType> layoutChangedTypes = new List<LayoutChangedType>();

        private bool isLocked;

        private bool isChanged;

        private bool canSave;

        private object restoringLock = new object();

        private List<PropertyChangeNotifier> propertyChangeNotifiers;

        public event EventHandler<LayoutChangedEventArgs> LayoutChanged;

        public string FileName { get; set; }

        protected override void OnCleanup()
        {
            canSave = false;
            UnSubscribeColumns();
            AssociatedObject.SortInfo.CollectionChanged -= OnSortInfoChanged;
            AssociatedObject.FilterChanged -= OnGridFilterChanged;
            AssociatedObject.AutoGeneratedColumns -= OnGridColumnsPopulated;
        }

        protected override void OnSetup()
        {
            RestoreLayout();
            SubscribeColumns();
            AssociatedObject.SortInfo.CollectionChanged += OnSortInfoChanged;
            AssociatedObject.FilterChanged += OnGridFilterChanged;
            AssociatedObject.AutoGeneratedColumns += OnGridColumnsPopulated;
        }

        private void RestoreLayout()
        {
            if (canSave || AssociatedObject.Columns.Count < 1)
            {
                return;
            }

            lock (restoringLock)
            {
                if (canSave)
                {
                    return;
                }

                string filePath = GetFilePath(FileName);

                if (File.Exists(filePath))
                {
                    AssociatedObject.RestoreLayoutFromXml(filePath);
                }

                canSave = true;
            }
        }

        private static string GetFilePath(string fileName)
        {
            string directoryPath = Path.Combine(ApplicationFolders.LocalApplicationData, "layouts");

            if (!Directory.Exists(directoryPath))
            {
                Directory.CreateDirectory(directoryPath);
            }

            return Path.Combine(directoryPath, fileName);
        }

        private void ColumnsCollectionChanged(object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
        {
            Task.Factory.StartNew(async () =>
            {
                await Task.Delay(2000);

                Dispatcher.BeginInvoke(new Action(RestoreLayout));
            });

            if (e.NewItems != null || e.OldItems != null)
            {
                ProcessLayoutChanging(LayoutChangedType.ColumnsCollection);
            }

            if (e.NewItems != null)
            {
                foreach (GridColumn column in e.NewItems)
                {
                    SubscribeColumn(column);
                }
            }
        }

        private void SaveLayout()
        {
            if (!canSave)
            {
                return;
            }

            string filePath = GetFilePath(FileName);
            try
            {
                AssociatedObject.SaveLayoutToXml(filePath);
            }
            catch
            {
                // ignored
            }
        }

        private void OnColumnGroupIndexChanged(object sender, EventArgs args)
        {
            ProcessLayoutChanging(LayoutChangedType.ColumnGroupIndex);
        }

        private void OnColumnVisibleChanged(object sender, EventArgs args)
        {
            ProcessLayoutChanging(LayoutChangedType.ColumnVisible);
        }

        private void OnColumnVisibleIndexChanged(object sender, EventArgs args)
        {
            ProcessLayoutChanging(LayoutChangedType.ColumnVisibleIndex);
        }

        private void OnColumnWidthChanged(object sender, EventArgs args)
        {
            ProcessLayoutChanging(LayoutChangedType.ColumnWidth);
        }

        private void OnGridColumnsPopulated(object sender, RoutedEventArgs e)
        {
            ProcessLayoutChanging(LayoutChangedType.ColumnsCollection);
            SubscribeColumns();
        }

        private void OnGridFilterChanged(object sender, RoutedEventArgs e)
        {
            ProcessLayoutChanging(LayoutChangedType.FilerChanged);
        }

        private void OnSortInfoChanged(object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
        {
            ProcessLayoutChanging(LayoutChangedType.SortingChanged);
        }

        private void ProcessLayoutChanging(LayoutChangedType type)
        {
            if (!layoutChangedTypes.Contains(type))
            {
                layoutChangedTypes.Add(type);
            }

            if (isLocked)
            {
                isChanged = true;
                return;
            }

            isChanged = false;
            isLocked = true;

            SaveLayout();

            Dispatcher.BeginInvoke(new Action(() =>
            {
                isLocked = false;
                LayoutChanged?.Invoke(this, new LayoutChangedEventArgs(layoutChangedTypes));
                layoutChangedTypes.Clear();

                if (isChanged)
                {
                    SaveLayout();
                }
            }));
        }

        private void SubscribeColumn(GridColumn column)
        {
            PropertyChangeNotifier actualWidthDescriptor = new PropertyChangeNotifier(column, "ActualWidth");
            actualWidthDescriptor.ValueChanged += OnColumnWidthChanged;
            propertyChangeNotifiers.Add(actualWidthDescriptor);

            PropertyChangeNotifier visibleIndexDescriptor = new PropertyChangeNotifier(column, "VisibleIndex");
            visibleIndexDescriptor.ValueChanged += OnColumnVisibleIndexChanged;
            propertyChangeNotifiers.Add(visibleIndexDescriptor);

            PropertyChangeNotifier groupIndexDescriptor = new PropertyChangeNotifier(column, "GroupIndex");
            groupIndexDescriptor.ValueChanged += OnColumnGroupIndexChanged;
            propertyChangeNotifiers.Add(groupIndexDescriptor);

            PropertyChangeNotifier visibleDescriptor = new PropertyChangeNotifier(column, "Visible");
            visibleDescriptor.ValueChanged += OnColumnVisibleChanged;
            propertyChangeNotifiers.Add(visibleDescriptor);
        }

        private void SubscribeColumns()
        {
            AssociatedObject.Columns.CollectionChanged += ColumnsCollectionChanged;

            propertyChangeNotifiers = new List<PropertyChangeNotifier>();

            foreach (GridColumn column in AssociatedObject.Columns)
            {
                SubscribeColumn(column);
            }
        }

        private void UnSubscribeColumns()
        {
            AssociatedObject.Columns.CollectionChanged -= ColumnsCollectionChanged;
        }
    }
}